### PR TITLE
Align test-cases with latest containers naming and availability

### PR DESCRIPTION
**Pull request by mvarlese**

### CODE REVIEW

**Review by evrardjp — APPROVED** [review]
That makes sense.

Was this framework convenient to use? Was the readme okay?

**Review by dcermak — DISMISSED** [review]
Let me squash a few commits, otherwise looks good to me.

**Comment by mvarlese** [comment]
> That makes sense.
> 
> Was this framework convenient to use? Was the readme okay?

Considered this is the 2nd time I write Python code... I think it was pretty straight forward  :)

**Comment by mvarlese** [comment]
> Let me squash a few commits, otherwise looks good to me.

I cannot see the changes you requested...

**Comment by evrardjp** [comment]
I think a `git rebase -i main` and replacing all the words with 's' + a `git push origin HEAD -f ` would do what @dcermak proposes.

**Comment by dcermak** [comment]
> I think a `git rebase -i main` and replacing all the words with 's' + a `git push origin HEAD -f ` would do what @dcermak proposes.

I already did that.

**Review by evrardjp — APPROVED** [review]

**Review by dcermak — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
